### ISSUE TITLE
Non-rt build broken

### ISSUE THREAD

**Issue by vilukissa68** [soc-hub-fi/headsail-vp#14]
Looks like #12 breaks non-rt build required in headsail-bsp-ffi.

Steps to reproduce:
```
cd examples/headsail-bsp-ffi
just build-hpc
```

Expected behaviour: ffi builds without any problems.

Observed behaviour:
```
error[E0432]: unresolved import `riscv`
 --> /Users/vainogranat/work/headsail-vp/examples/headsail-bsp/src/lib.rs:9:9
  |
9 | pub use riscv;
  |         ^^^^^ no external crate `riscv`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `headsail-bsp` (lib) due to 1 previous error
error: Recipe `build-hpc` failed on line 5 with exit code 101
```

**Comment by hegza** [comment]
Alright. Good catch. Fixed with proper conditional compilation tag. I think we should also add the FFI build to CI to prevent merges causing your code to break :)

I'll get to it asap.
