### ISSUE TITLE
Renode UART analyzer hangs after 1024 bytes

### ISSUE THREAD

**Issue by vilukissa68** [soc-hub-fi/headsail-vp#38]
When printing over 1024 bytes to UART with `sprintln!` or `sprint!` macroes the Renode UART analyzer hangs, which causes Renode to freeze. It would be nice to be able to print indefinite amounts of data to UART.

**Comment by vilukissa68** [comment]
This is a documented issue in Renode: [https://github.com/renode/renode/issues/389](https://github.com/renode/renode/issues/389). The workaround is to disable the Renode analyzer and connect directly to the Pty Terminal instance. For headsail VP this can be done by first commenting out lines
```repl
showAnalyzer sysbus.apb_uart_0
showAnalyzer sysbus.apb_uart_1
```
In the scripts/resc/0_mach_create.resc file

Connecting to Renode serial can be done with screen:
```sh
screen /tmp/uart0
screen /tmp/uart1
```

**Comment by hegza** [comment]
Nice work finding that out. I've been running into this every now and then.
